//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplCEEHACk.DbModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class RecordsList
    {
        //if problems delate
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int recordID { get; set; }
        public Nullable<int> patientID { get; set; }
        public Nullable<System.DateTime> actualTime { get; set; }
        public Nullable<System.DateTime> lastApttTime { get; set; }
        public Nullable<float> lastAptt { get; set; }
        public Nullable<float> actualAptt { get; set; }
        public Nullable<float> submitedAptt { get; set; }
        public Nullable<float> recomendedAptt { get; set; }
    
        public virtual PatientsList PatientsList { get; set; }
    }
}
